FROM nginx:alpine

# Remove default nginx config
RUN rm /etc/nginx/conf.d/default.conf

# Copy our custom config
COPY nginx.conf /etc/nginx/conf.d/cusdis-proxy.conf

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]
